apiVersion: v1
kind: Secret
metadata:
  name: rimo-secret
  namespace: default

type: Opaque

stringData:
  DB_USERNAME: "team4"
  DB_PASSWORD: "Gkrtod1@"

  JWT_SECRET: "CHANGE_ME"

  SOLAPI_API_KEY: "CHANGE_ME"
  SOLAPI_API_SECRET: "CHANGE_ME"
  SOLAPI_SENDER: "CHANGE_ME"

  KAKAO_REST_API_KEY: "CHANGE_ME"
  KAKAO_MOBILITY_REST_API_KEY: "CHANGE_ME"

  GEMINI_API_KEY: "CHANGE_ME"
